version: "3.8"

networks:
  banner:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-banner:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admax
      - POSTGRES_DB=banner
    networks:
      - banner
  app:
    build: .
    command: ./bin/banners
    networks:
      - banner
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - CONFIG=./config/docker.yaml
volumes:
  postgres-banner:
    driver: local


